version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: /
    labels:
      - dependencies
    schedule:
      interval: monthly
