[workspace]
resolver = "2"
members = [
  "wacker",
  "wacker-api",
  "wacker-cli",
]

[workspace.package]
version = "0.1.3"
authors = ["Xinzhao Xu"]
edition = "2021"
categories = ["wasm"]
keywords = ["webassembly", "wasm", "wasi"]
repository = "https://github.com/iawia002/wacker"
license = "Apache-2.0"

[workspace.dependencies]
wacker-api = { path = "wacker-api", version = "0.1.3" }

anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
dirs = "5.0.1"
tokio = { version = "1.34.0", features = ["rt", "rt-multi-thread", "macros"] }
tonic = "0.10.2"
