[workspace]
resolver = "2"
members = [
  "wacker",
  "wacker-daemon",
  "wacker-cli",
]

[workspace.package]
version = "0.3.0"
authors = ["Xinzhao Xu"]
edition = "2021"
categories = ["wasm"]
keywords = ["webassembly", "wasm", "wasi"]
repository = "https://github.com/iawia002/wacker"
license = "Apache-2.0"

[workspace.dependencies]
wacker = { path = "wacker", version = "0.3.0" }

anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
log = "0.4.20"
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
tonic = { version = "0.11.0", features = ["zstd"] }
