[package]
name = "wacker"
description = "wacker core"
readme = "../README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap.workspace = true
log.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true

dirs = "5.0.1"
wasi-common = "16.0.0"
wasmtime = "17.0.0"
wasmtime-wasi = { version = "16.0.0", features = ["tokio"] }
cap-std = "2.0.0"
rand = "0.8.5"
sled = "0.34.7"
tower = "0.4.13"
prost = "0.12.3"
const_format = "0.2.32"
async-stream = "0.3.5"

[build-dependencies]
anyhow.workspace = true
tonic-build = "0.10.2"
