[package]
name = "wacker"
description = "wacker daemon"
readme = "../README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "wackerd"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wacker-api = { path = "../wacker-api", version = "0.1.1" }
anyhow = "1.0.75"
tokio = { version = "1.34.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
wasi-common = "15.0.0"
wasmtime = { version = "15.0.1", features = ["cranelift"] }
wasmtime-wasi = { version = "15.0.0", features = ["tokio"] }
tonic = "0.10.2"
dirs = "5.0.1"
log = "0.4.20"
env_logger = "0.10.1"
cap-std = "2.0.0"
rand = "0.8.5"
sled = "0.34.7"
