[package]
name = "wacker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
tokio = { version = "1.33.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-stream = {  version = "0.1.14", features = ["net"] }
wasi-common = "14.0.3"
wasmtime = { version = "14.0.3", features = ["cranelift"] }
wasmtime-wasi = { version = "14.0.3", features = ["tokio"] }
tonic = "0.10.2"
dirs = "5.0"
wacker-api = { path = "../wacker-api" }
log = "0.4.20"
env_logger = "0.10.0"
cap-std = "2.0.0"
rand = "0.8.5"
