name: CI
on:
  push:
    branches:
      - 'main'
      - 'release-**'
  pull_request:
jobs:
  ci:
    name: Lint and unit test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: clippy, rustfmt
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: cargo test
        run: cargo test --workspace -- --test-threads=2
